# Generated by Django 3.2.4 on 2021-06-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cost_freq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.costfreq', verbose_name='Czestotliwosc kosztow'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.category', verbose_name='Kategoria'),
        ),
    ]
